### ISSUE TITLE
Sealer pull faied in container，operation not permitted

### ISSUE THREAD

**Issue by fanux** [alibaba/sealer#1187]
The container dockerfile:
```
[root@iZ2ze511twyevmbygeox5tZ test]# cat Dockerfile 
FROM ubuntu

RUN apt update && \
    apt install -y make && \
    apt install -y tree
RUN apt-get update && \
   apt-get install ca-certificates -y && \
   update-ca-certificates
COPY ./sealer /usr/bin 
RUN chmod +x /usr/bin/sealer
```

build the docker image:

`docker build -t sealer-env .`

run container:

`docker run --rm sealer-env sealer pull kubernetes:v1.19.8`

Got error:
```
root@696b03215da0:~# sealer pull kubernetes:v1.19.8  
Start to Pull Image kubernetes:v1.19.8
a8d197c0285c: pull completed 
1dfe57535815: operation not permitted 
61f2252f2145: operation not permitted 
Error: failed to pull image kubernetes:v1.19.8, err: operation not permitted
Usage:
  sealer pull [flags]

Examples:
sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8

Flags:
  -h, --help   help for pull

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode

failed to pull image kubernetes:v1.19.8, err: operation not permitted
```

**Comment by kakaZhou719** [comment]
docker run -itd --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --device /dev/fuse --detach --tty --restart=on-failure:1 --init=false registry.cn-qingdao.aliyuncs.com/sealer-io/sealer-base-image:latest

**Comment by fanux** [comment]
`docker run -it --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --volume /var --volume /lib/modules:/lib/modules:ro --dece /dev/fuse sealer  sealer pull kubernetes:v1.19.8`  sucessed

**Comment by fanux** [comment]
`docker run --rm -it --privileged --volume /var --volume /lib/modules:/lib/modules:ro sealer:latest  sealer pull kubernetes:v1.19.8`

**Comment by fanux** [comment]
```
[root@iZ2ze511twyevmbygeox5tZ ~]# docker run -v /root/test:/test -it --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --device /dev/fuse sealer bash

root@2235c52fd58d:/test# sealer build -t test .
Start to Pull Image kubernetes:v1.19.8
a8d197c0285c: pull completed 
1dfe57535815: pull completed 
61f2252f2145: pull completed 
Success to Pull Image kubernetes:v1.19.8
2022-02-28 06:23:12 [INFO] [build_image.go:67] run build layer: COPY sealer /bin
panic: no ':' separator in digest ""

goroutine 1 [running]:
github.com/opencontainers/go-digest.Digest.sepIndex(0x0, 0x0, 0x7fef4412fd58)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/opencontainers/go-digest/digest.go:153 +0x105
github.com/opencontainers/go-digest.Digest.Algorithm(...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/opencontainers/go-digest/digest.go:122
github.com/alibaba/sealer/image/store.(*filesystem).LayerDBDir(0xc00069bc20, 0x0, 0x0, 0x9, 0x0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/image/store/filesystem.go:255 +0x3c
github.com/alibaba/sealer/image/store.(*filesystem).SetMetadata(0xc00069bc20, 0x0, 0x0, 0x3e2dd43, 0x7, 0xc00016c190, 0x47, 0x50, 0x0, 0x0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/image/store/filesystem.go:227 +0x9e
github.com/alibaba/sealer/build/buildkit/buildinstruction.CopyInstruction.SetCacheID(...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/build/buildkit/buildinstruction/copy.go:122
github.com/alibaba/sealer/build/buildkit/buildinstruction.CopyInstruction.Exec(0xc000618215, 0x6, 0xc00061821d, 0x3, 0x0, 0x0, 0xc000618210, 0x4, 0xc000618215, 0xb, ...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/build/buildkit/buildinstruction/copy.go:101 +0xac2
github.com/alibaba/sealer/build/buildkit/buildimage.BuildImage.ExecBuild(0xc00011eb60, 0xc0004440f0, 0x5, 0x5, 0xc000436630, 0x1, 0x1, 0x41a6b48, 0xc0005cecb0, 0x41937e0, ...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/build/buildkit/buildimage/build_image.go:83 +0x475
github.com/alibaba/sealer/build/lite.(*Builder).ExecBuild(...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/build/lite/lite_builder.go:94
github.com/alibaba/sealer/build/lite.(*Builder).Build(0xc000247c20, 0x7ffc1d28c964, 0x4, 0x7ffc1d28c969, 0x1, 0x3e2f407, 0x8, 0x3e35185, 0xc)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/build/lite/lite_builder.go:65 +0x436
github.com/alibaba/sealer/sealer/cmd.glob..func2(0x5d1f260, 0xc0005cd7a0, 0x1, 0x3, 0x0, 0x0)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/build.go:72 +0x10d
github.com/spf13/cobra.(*Command).execute(0x5d1f260, 0xc0005cd770, 0x3, 0x3, 0x5d1f260, 0xc0005cd770)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x5d20660, 0x20, 0x6, 0x7)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/vendor/github.com/spf13/cobra/command.go:897
github.com/alibaba/sealer/sealer/cmd.Execute()
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/cmd/root.go:47 +0x31
main.main()
	/home/runner/work/sealer/sealer/src/github.com/alibaba/sealer/sealer/main.go:26 +0x35
```

**Comment by kakaZhou719** [comment]
FROM ubuntu:21.04

RUN echo "Installing Packages ..." \
    && sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       kmod ca-certificates \
    && apt-get clean -y                                               \
    && rm -rf                                                         \
       /var/cache/debconf/*                                           \
       /var/lib/apt/lists/*                                           \
       /var/log/*                                                     \
       /tmp/*                                                         \
       /var/tmp/*                                                     \
       /usr/share/doc/*                                               \
       /usr/share/man/*                                               \
       /usr/share/local/*                                             \
    && rm -f /lib/systemd/system/multi-user.target.wants/* \
    && rm -f /etc/systemd/system/*.wants/* \
    && rm -f /lib/systemd/system/local-fs.target.wants/* \
    && rm -f /lib/systemd/system/sockets.target.wants/*udev* \
    && rm -f /lib/systemd/system/sockets.target.wants/*initctl* \
    && rm -f /lib/systemd/system/basic.target.wants/*

ENTRYPOINT [ "/bin/bash" ]
